
DROP TABLE IF EXISTS TIME_DATA;
CREATE TABLE TIME_DATA (	
	dt DATE
	,dt_tm DATETIME
	,tmsp TIMESTAMP
    ,tm TIME
    ,yyyy YEAR(4)    
    );

/* 
SET SQL_SAFE_UPDATES = 0;
DELETE FROM TIME_DATA;
*/

INSERT INTO TIME_DATA VALUES (CURDATE(), NOW(), CURTIME(), NOW(),  '00' ); -- 2000
INSERT INTO TIME_DATA VALUES (CURDATE(), NOW(), CURTIME(), NOW(), 00 );    -- 0
INSERT INTO TIME_DATA VALUES (CURDATE(), NOW(), CURTIME(), NOW(),  '05' );  -- 2005
INSERT INTO TIME_DATA VALUES (CURDATE(), NOW(), CURTIME(), NOW(),  '7' );
INSERT INTO TIME_DATA VALUES (CURDATE(), NOW(), CURTIME(), NOW(),  '10' );
INSERT INTO TIME_DATA VALUES (CURDATE(), NOW(), CURTIME(), NOW(),  '69' );
INSERT INTO TIME_DATA VALUES (CURDATE(), NOW(), CURTIME(), NOW(),  '70' );
INSERT INTO TIME_DATA VALUES (CURDATE(), NOW(), CURTIME(), NOW(),  '80' );
INSERT INTO TIME_DATA VALUES (CURDATE(), NOW(), CURTIME(), NOW(),  '90' );
INSERT INTO TIME_DATA VALUES (CURDATE(), NOW(), CURTIME(), NOW(),  '99' );
-- INSERT INTO TIME_DATA VALUES (CURDATE(), NOW(), CURTIME(), NOW(),  '999' ); -- error  of range
-- INSERT INTO TIME_DATA VALUES (CURDATE(), NOW(), CURTIME(), NOW(),  '1199' );   -- error  of range
INSERT INTO TIME_DATA VALUES (CURDATE(), NOW(), CURTIME(), NOW(),  '2155' );   
-- INSERT INTO TIME_DATA VALUES (CURDATE(), NOW(), CURTIME(), NOW(),  '2156 ' );   -- rror  of range MAX
INSERT INTO TIME_DATA VALUES (CURDATE(), NOW(), CURTIME(), NOW(),  '2000' );
INSERT INTO TIME_DATA VALUES (CURDATE(), NOW(), CURTIME(), NOW(),  '0000' );
INSERT INTO TIME_DATA VALUES ('2023-11-16', NOW(), CURTIME(), NOW(),  '2023' );
INSERT INTO TIME_DATA VALUES (NOW(), NOW(), CURTIME(), NOW(),  '1970' ); -- warning using now() assign to date (truncate time)
INSERT INTO TIME_DATA VALUES (CURDATE(), NOW(), CURTIME(), NOW(), 2023 );
INSERT INTO TIME_DATA VALUES (20231126, NOW(), CURTIME(), NOW(), 2023 );
-- INSERT INTO TIME_DATA VALUES (20232611, NOW(), CURTIME(), NOW(), 2023 ); -- error month cant be 26
-- INSERT INTO TIME_DATA VALUES (202311, NOW(), CURTIME(), NOW(), 2023 ); -- error missing date dd
INSERT INTO TIME_DATA VALUES (20231100, NOW(), CURTIME(), NOW(), 2023 ); -- dd as 00 - works! :O
-- INSERT INTO TIME_DATA VALUES (2023/11/25, NOW(), CURTIME(), NOW(), 2023 ); -- dont like it
INSERT INTO TIME_DATA VALUES ('2023/11/27', NOW(), CURTIME(), NOW(), 2023 ); -- yup!
INSERT INTO TIME_DATA VALUES ('2023.11.27', NOW(), CURTIME(), NOW(), 2023 ); -- works but abnormal
    
SELECT * FROM TIME_DATA;