# Dockerfile to setup 2 images: mysql & adminer
# This is intended as an excercise and NOT reconmmended for a Production environment!
# Date: Oct 15, 2023
#
# Start containers (make sure docker desktop, or dockerd, is running first)
#   $ docker-compose up -d
# Check containers up running 
#   $ docker ps
# Stop container 
#   $ docker stop adminer mysql
# Remove container 
#   $ docker rm adminer mysql
#
#   $ docker-compose down     # this will stop and remove containers
#
# Test site when image is running via localhost:8080
#   Enter the id, pwd and db name as below in db service
#  Create a SQL table, Table1: CREATE TABLE Table1 (ID INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(50) NOT NULL);
#  Insert some data into Table1
#    INSERT INTO Table1 (Name) VALUES ('Joe'),('Mary');
#    SELECT * FROM Table1;


version: '3.5'

services:
  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      # When container is first created, this database and superuser are created
      MYSQL_DATABASE: yorku_csfs1030
      MYSQL_USER: csfs1030
      MYSQL_PASSWORD: csfs1030
    ports:
      - 3308:3306
    volumes:
      - ./sql:/media # Shared folder, just in case
      - ./sql:/docker-entrypoint-initdb.d # Scripts in this folder are run automatically at container creation
      # - ./sql/data:/var/lib/mysql # MySQL data folder
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080      # you can access: localhost:8080
    depends_on:
      - db
      
      
 
# Common error:
#  $ docker ps 
#  error during connect: this error may indicate that the docker daemon is 
#  not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json": open //./pipe/docker_engine: The system cannot find the file specified.
# Solution: start docker demon or docker desktop
 